/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        surface: '#ffffff',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#464554',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'surface-tint': '#494bd6',
        primary: '#4648d4',
        'on-primary': '#ffffff',
        'primary-container': '#6063ee',
        'on-primary-container': '#fffbff',
        'primary-50': '#eef2ff',
        'primary-100': '#e0e7ff',
        'primary-500': '#6366f1',
        'primary-600': '#4f46e5',
        'primary-700': '#4338ca',
        'bg-primary': '#f8fafc',
        'bg-secondary': '#f1f5f9',
        'text-primary': '#0f172a',
        'text-secondary': '#475569',
        'text-muted': '#94a3b8',
        'text-disabled': '#cbd5e1',
        'border-default': '#e2e8f0',
        'border-subtle': '#f1f5f9',
        'border-strong': '#cbd5e1',
        'semantic-green': '#10b981',
        'semantic-green-soft': '#ecfdf5',
        'semantic-rose': '#f43f5e',
        'semantic-rose-soft': '#fff1f2',
        'semantic-amber': '#f59e0b',
        'semantic-amber-soft': '#fffbeb',
        'semantic-blue': '#3b82f6',
        'semantic-blue-soft': '#eff6ff',
      },
    },
  },
  plugins: [],
}
